### PR TITLE
support x86 and x64 build outputs

### PR DESCRIPTION
**Pull request by IRebo**
not really intended for merging but if someone needs x86 they can try this fork

-the build produces 2 build outputs so if someone (like me) needs the x86 one its possible to make use of it
-fix crashing when calling SetCustData in x86 mode
-i still have yet to check if the produced tlb works correctly :)

### CODE REVIEW

**Comment by SOsterbrink** [comment]
Hi @IRebo , 
thanks you for your contribution. We will check whether your changes would work, what is still missing and whether we can include your changes into the master. At a first glance there are some things missing, like a command line switch for 32 bit and some dedicated unit tests for these scenarios. 
Checking this will take some time because of the amount of the possible test cases which would have to be checked.

**Comment by marklechtermann** [comment]
related to #59

**Comment by marklechtermann** [comment]
#59

**Comment by marklechtermann** [comment]
#60

**Comment by marklechtermann** [comment]
32Bit assemblie are now supported!
If you have an "AnyCPU" assembly, then you can create a 32Bit TLB with the switch "--win32".
If your assembly is a 32bit assembly, then the "dscom32.exe" must be used.
This can be downloaded from the release page.
https://github.com/dspace-group/dscom/releases

**Pull request closed without merging**
