### PR TITLE
feat: Support for inline attributes and aliasing

### PR DESCRIPTION
**Pull request by bclothier**
This PR introduces the ability to decorate the assembly with custom attributes that are not provided by the original .NET framework, which allow us to bridge gaps that was present even from the .NET framework and also to shape the type library using attributes which is a great help in keeping the code documented. 3 new attributes are introduced:

* `Hidden` attribute which decorates the type as hidden from the object browser of the tools. 
* `Restricted` attribute which prevents the scripting tools from using the type while still exposing it to COM. 
* `ComAlias` attribute which allows aliasing of the elements to be exported into the type library. 

Because the `dscom` already has support for `Names`, it was necessary to adapt the `NameResolver` so that it can support different strategies with preference toward the original `Names`. To support this, the name resolver has been revamped into an interface to help hide the implementation details and various writers has been updated to pass back the reflection objects (e.g. `Type`, `MethodInfo`, `PropertyInfo`, etc.) as to help with the mapping of the types. The original name resolution strategy has been renamed into `SimpleNameResolver` and continue to use the `Dictionary<string, string>` based on the text files or a provided `IEnumerable<string>` in memory. The `ComAliasNameResolver` implements the new strategy for mapping the `ComAlias` attribute and providing the alias for the elements.

Note that it is valid to use a completely different name for enumerations and constants because the names do not across the interop boundaries. Therefore, it is possible to use `ComAlias` to provide a more friendly name to enumerations. Therefore, we can expose a .NET enum such as:

```
[
    ComVisible(true),
    ComAlias("FrooFroo")
]
public enum Fruits
{
    [ComAlias("frApple")]
    Apple,
    [ComAlias("frBanana")]
    Banana,
    [ComAlias("frCherry")]
    Cherry
}
```

and export it via type library as thus:
```
    enum {
        frApple = 0,
        frBanana = 1,
        frCherry = 2
    } FrooFroo;
```

which is more idiomatic with the scripting language than .NET's original approach of `Fruits_Apple`. However, using `ComAlias` places the responsibility on the user to ensure that the enumeration name is unique within the library. A future enhancement would to be add an analyzer to validate that the alias is permissible and valid.

### CODE REVIEW

**Comment by bclothier** [comment]
Two additional notes:

1) If we don't want the attributes to cause runtime dependency, we can consider implementing something similar to this: [Using marker attributes without runtime dependency](https://andrewlock.net/creating-a-source-generator-part-4-customising-generated-code-with-marker-attributes/) but with the following caveats:
    * The metadata would be lost and thus cannot be used by the client tool unless we extract the information at the compile time and build a file to be as an input into the client code.
    * Alternatively, we can modify the library to run as a source generator rather than as a build task. Unfortunately that might be complicated because that means working with Roslyn API rather than Reflection to write the library. This still limits the usefulness of the CLI tool. [This might be useful to reduce the effort for using as a source generator](https://github.com/davidfowl/Roslyn.Reflection).

2) After thinking about it some, I believe I am missing some unit tests. Normally I do not do that; only the enumeration members is enough in my use case. However, renaming the enumeration may affect references such as:
```
Fruits GetFruit(optional Fruits PreferredFruit = Fruits.Cherry)
```
So need to  create unit tests to cover that case to ensure that the type library will be exported correctly even with the renaming of the constants. I will add them shortly.

**Comment by bclothier** [comment]
Just added the unit test to demonstrate the scenario where enum is referenced to prove that aliasing will not break the type library. The example is a bit more extreme because I normally don't rename the enumerations; only the enumeration members but that at least reassure that there is no problem doing so because of the fact that the enumerations are nothing more than a glorified `int` constants and its value is compiled inline and its name provided within the type library without reference to the assembly. 

Prior to setting up the unit test, I also did an example by hand to prove that the assertion is true. However, I am not sure whether it needs to be added to the examples folder because of relative complexity in setting up the example correctly. For now, I'm attaching it as a zip so that you can also review and assess the effect. Note that to test all 3 examples, you will need to have C++ build toolchain in order to run the MIDL for the 2nd example. 

For the examples to work, they need to be extracted into the `examples` with the `enumAlias` as the containing folder. Each exxample has a `Register.bat` and corresponding `Unregister.bat` that can be run before & after the demonstration. I chose to use an Excel macro-enabled worksheet `EnumAlias.xlsm` because this need to be done using early-binding with references. Each worksheet are identical except in the reference (they reference the `.tlb` generated in the same containing folder). 

The three examples are as following:
* `01 original output`: Provides the baseline from .NET 4.8 FX using `Regasm.exe` and the default behavior of enum namings. 
* `02 edited via midl`: Similar to previous except that in addition to the `Regasm.exe`, it compiles the modified IDL file which has modified the relevant objects using MIDL to generate the type library and replaces the generated .`tlb` file with the modified `.tlb` file. This demonstrates that even though registration was done using `Regasm.exe` and Excel was using the modified `.tlb` file, it still works nonetheless, showing that the enum names do not in fact cross the interop boundary.
* `03 decorated with attributes`: This is the .NET 6.0 build using the attributes by running through the `dscom` CLI to export the type library and executing `regsvr32` on the `comhost.dll` to demonstrate that this still works even with the aliasing being done on the enum itself and its members. 

Please let me know if you'd rather include the examples in the repository and I'll be happy to do so; the requirement to have MIDL may be an obstacle in demonstrating fully the potential. 

[Enum Alias Examples.zip](https://github.com/dspace-group/dscom/files/10610228/Enum.Alias.Examples.zip)

**Comment by SOsterbrink** [comment]
Hi @bclothier, 

thanks for your contribution.  

I don't think we need the additional examples because those will bring unwanted dependencies. If you have the time, you could add these examples to a Gist and send us the link, so that we can include it in our documentation. The current examples should be sufficient for this. 

Most of the stuff looks very good, but some of the code style checks are failing. That's nothing big, but it would be good if you can fix those. 
There are also some issues with our MsBuild task, where @carstencodes will contact you.  

After those are handled, we can close and merge the pull request.

**Comment by bclothier** [comment]
Thanks, is there a way to run the same code style check locally to verify I've fixed them all?

**Comment by marklechtermann** [comment]
You can simply run the following command:

```bash
dotnet format --verify-no-changes
``` 

And thanks for your support!

**Comment by carstencodes** [comment]
Hello @bclothier,

I've noticed that the build task only supports build-in Com Aliases within the assembly. Is this intentional? Should we add the naming support here as well?

Are you capable of doing that or should I take care of this?

Regards

**Comment by bclothier** [comment]
No, it's likely a misunderstanding on my part. The original version did not appear to be taking in the `Names` input so I assumed that the build task was not supporting the `Names` originally. If it's in fact taking in the `Names` as an input, then the changes on the build task need to be similar to the CLI version where `Names` take precedence and select the `SimpleNameResolver` over `ComAliasResolver`. I added the Com Alias primarily because if we are able to able to use the build task without relying on the CLI too, it would be able to access the metadata at compile-time without creating a runtime dependency.

**Comment by carstencodes** [comment]
@bclothier Yeah, my mistake. I was unaware of the Names Option in the first Place. I can add support afterwards...

**Comment by bclothier** [comment]
> I don't think we need the additional examples because those will bring unwanted dependencies. If you have the time, you could add these examples to a Gist and send us the link, so that we can include it in our documentation. The current examples should be sufficient for this.

While I'm happy to do this, I want you to be aware that currently the link is already in your repository. The link above leads to this address:

```
https://github.com/dspace-group/dscom/files/10610228/Enum.Alias.Examples.zip
```

Therefore, it would be in your control to keep and even update if so desired. Would that be preferable to a gist? 

> Most of the stuff looks very good, but some of the code style checks are failing. That's nothing big, but it would be good if you can fix those. There are also some issues with our MsBuild task, where @carstencodes will contact you.
> 
> After those are handled, we can close and merge the pull request.

Thanks for the feedback. I've corrected the code style formatting and also added the support for names in the build task. I hope that meets all the requirements.

**Comment by marklechtermann** [comment]
[https://github.com/dspace-group/dscom/releases/tag/v0.20.0](https://github.com/dspace-group/dscom/releases/tag/v0.20.0)

**Pull request merged**
